#!/usr/bin/env python3
"""Streamlit dashboard for Susan AI hybrid-search weight grid reports."""

from __future__ import annotations

import json
from io import BytesIO, StringIO
from pathlib import Path
from typing import Any

import pandas as pd
import plotly.express as px
import streamlit as st


st.set_page_config(page_title="Susan AI · Search Weight Lab", page_icon="🔎", layout="wide")


def load_json(data: bytes) -> dict[str, Any]:
    payload = json.loads(data.decode("utf-8"))
    if not isinstance(payload, dict) or "all" not in payload:
        raise ValueError("This does not look like a search-weight-grid JSON report.")
    return payload


def load_csv(data: bytes) -> dict[str, Any]:
    frame = pd.read_csv(StringIO(data.decode("utf-8")))
    required = {"semanticWeight", "keywordWeight", "stabilityWeight", "score"}
    if not required.issubset(frame.columns):
        raise ValueError(f"CSV must contain: {', '.join(sorted(required))}")
    rows = frame.to_dict(orient="records")
    best = max(rows, key=lambda row: float(row["score"])) if rows else None
    return {"config": {"metric": "score", "evaluatedConfigurations": len(rows)}, "default": None, "best": best, "top": rows[:10], "all": rows}


@st.cache_data(show_spinner=False)
def parse_upload(name: str, data: bytes) -> dict[str, Any]:
    return load_csv(data) if name.lower().endswith(".csv") else load_json(data)


def frame_from_report(report: dict[str, Any]) -> pd.DataFrame:
    frame = pd.DataFrame(report.get("all", []))
    for column in ("semanticWeight", "keywordWeight", "stabilityWeight", "score"):
        if column in frame:
            frame[column] = pd.to_numeric(frame[column], errors="coerce")
    return frame.dropna(subset=["semanticWeight", "keywordWeight", "score"])


def format_weight(value: Any) -> str:
    return "—" if value is None else f"{float(value):.2f}"


def metric_label(report: dict[str, Any]) -> str:
    return str(report.get("config", {}).get("metric", "optimized metric"))


def main() -> None:
    st.markdown("# Search Weight Lab")
    st.caption("Offline relevance analysis for Susan AI hybrid search · keyword + semantic + rank stability")

    with st.sidebar:
        st.header("Load report")
        upload = st.file_uploader("Upload grid-search JSON or CSV", type=["json", "csv"])
        st.markdown("Generate a report with:")
        st.code("python3 scripts/search-weight-grid.py \\\n  --dataset data/search-relevance.json \\\n  --metric ndcg@5 \\\n  --output-json reports/weight-grid.json", language="bash")
        st.divider()
        st.markdown("**Interpretation**")
        st.caption("Use a labeled qrels dataset. The best weight is only as reliable as the queries and relevance judgments used to produce it.")

    if not upload:
        st.info("Upload a report generated by `search-weight-grid.py` to begin.")
        st.stop()

    try:
        report = parse_upload(upload.name, upload.getvalue())
        frame = frame_from_report(report)
    except (ValueError, json.JSONDecodeError) as error:
        st.error(str(error))
        st.stop()

    if frame.empty:
        st.warning("The report contains no valid grid configurations.")
        st.stop()

    metric = metric_label(report)
    best = report.get("best") or frame.sort_values("score", ascending=False).iloc[0].to_dict()
    default = report.get("default")
    best_score = float(best["score"])
    default_score = float(default["score"]) if default and default.get("score") is not None else None
    delta = best_score - default_score if default_score is not None else None

    st.subheader("Recommendation")
    cards = st.columns(4)
    cards[0].metric("Best semantic weight", format_weight(best.get("semanticWeight")))
    cards[1].metric("Best keyword weight", format_weight(best.get("keywordWeight")))
    cards[2].metric(metric, f"{best_score:.4f}")
    cards[3].metric("vs default 0.60 / 0.30 / 0.10", "—" if delta is None else f"{delta:+.4f}", delta=None if delta is None else f"{delta:+.4f}")

    st.caption(f"{len(frame)} configurations evaluated · optimized metric: `{metric}` · stability weight: `{format_weight(best.get('stabilityWeight'))}`")

    st.subheader("Weight landscape")
    left, right = st.columns([1.5, 1])
    with left:
        pivot = frame.pivot_table(index="semanticWeight", columns="keywordWeight", values="score", aggfunc="max")
        heatmap = px.imshow(
            pivot.sort_index(ascending=False),
            aspect="auto",
            color_continuous_scale="Viridis",
            labels={"x": "Keyword weight", "y": "Semantic weight", "color": metric},
            text_auto=".3f",
        )
        heatmap.update_layout(height=520, margin=dict(l=10, r=10, t=30, b=10), coloraxis_colorbar_title=metric)
        st.plotly_chart(heatmap, use_container_width=True)
    with right:
        line = px.line(
            frame.sort_values("semanticWeight"),
            x="semanticWeight",
            y="score",
            markers=True,
            hover_data=["keywordWeight", "stabilityWeight"],
            labels={"semanticWeight": "Semantic weight", "score": metric},
        )
        line.update_layout(height=520, margin=dict(l=10, r=10, t=30, b=10), showlegend=False)
        st.plotly_chart(line, use_container_width=True)

    st.subheader("Top configurations")
    top_count = st.slider("Rows", min_value=3, max_value=min(50, len(frame)), value=min(10, len(frame)))
    display = frame.sort_values(["score", "map", "mrr"] if {"map", "mrr"}.issubset(frame.columns) else ["score"], ascending=False).head(top_count).copy()
    display.insert(0, "rank", range(1, len(display) + 1))
    st.dataframe(display, use_container_width=True, hide_index=True)

    st.subheader("Configuration explorer")
    selected = st.selectbox("Select a semantic weight", sorted(frame["semanticWeight"].unique()))
    selected_rows = frame[frame["semanticWeight"] == selected].sort_values("score", ascending=False)
    st.dataframe(selected_rows, use_container_width=True, hide_index=True)

    report_bytes = json.dumps(report, ensure_ascii=False, indent=2).encode("utf-8")
    csv_bytes = frame.to_csv(index=False).encode("utf-8")
    st.download_button("Download loaded JSON", report_bytes, file_name="weight-grid-report.json", mime="application/json")
    st.download_button("Download configuration CSV", csv_bytes, file_name="weight-grid-configurations.csv", mime="text/csv")

    with st.expander("Methodology and caveats"):
        st.markdown(
            """
            - The dashboard visualizes the offline report; it does not call an embedding API.
            - The best configuration optimizes the selected metric on the uploaded qrels.
            - A small or biased query set can overfit. Validate the selected weights on a held-out query set before production rollout.
            - Compare `NDCG@5`, `MRR`, and `MAP` together instead of selecting a weight from a single metric blindly.
            """
        )


if __name__ == "__main__":
    main()
