"use client";
import { BarChart3, FileText, Paperclip, Plus, Send, Search, Sparkles, X } from "lucide-react";
import { useRef, useState } from "react";
import { AgentAttachment, AgentTask } from "@/lib/agent/types";

interface AgentBottomComposerProps { onCreateTask: (goal: string, attachments: AgentAttachment[]) => AgentTask | void | Promise<AgentTask | void>; activeTask: boolean; }
const ACCEPTED = /\.(txt|md|csv|json|pdf|docx|xlsx)$/i;
const MAX_FILE_SIZE = 4 * 1024 * 1024;
const QUICK_ACTIONS = [
  { label: "Analyze file", prompt: "Analyze the attached file and summarize the key findings.", icon: <FileText className="h-3.5 w-3.5" /> },
  { label: "Create chart", prompt: "Create charts from the attached data and explain the main trends.", icon: <BarChart3 className="h-3.5 w-3.5" /> },
  { label: "Generate report", prompt: "Generate a detailed report from the attached data with findings and recommendations.", icon: <FileText className="h-3.5 w-3.5" /> },
  { label: "Write document", prompt: "Write a polished document based on the task context.", icon: <Sparkles className="h-3.5 w-3.5" /> },
  { label: "Web search", prompt: "Search for the latest information relevant to this task.", icon: <Search className="h-3.5 w-3.5" /> },
];
export function AgentBottomComposer({ onCreateTask, activeTask }: AgentBottomComposerProps) {
  const [goal, setGoal] = useState("");
  const [files, setFiles] = useState<File[]>([]);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const clean = goal.trim(); if (!clean) return setError("Describe a goal for Susan AI first."); try { const attachments = await Promise.all(files.map(toAttachment)); await onCreateTask(clean, attachments); setGoal(""); setFiles([]); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not read the selected file."); } };
  const chooseFiles = (selected: FileList | null) => { if (!selected) return; const next = [...files]; for (const file of Array.from(selected)) { if (file.size > MAX_FILE_SIZE) { setError(`${file.name} is larger than 4 MB.`); continue; } if (!ACCEPTED.test(file.name)) { setError(`${file.name} is not supported.`); continue; } if (!next.some((item) => item.name === file.name && item.size === file.size)) next.push(file); } setFiles(next.slice(0, 3)); if (fileRef.current) fileRef.current.value = ""; };
  const handleQuickAction = (prompt: string) => { setGoal(prompt); inputRef.current?.focus(); };
  return <section aria-label="Persistent Agent input" className="sticky bottom-0 z-20 border-t border-border-main/70 bg-bg-main/95 px-3 pb-3 pt-2 backdrop-blur-md md:px-6"><form onSubmit={(event) => void submit(event)} className="mx-auto max-w-5xl"><div className="rounded-2xl border border-border-main/80 bg-surface p-2 shadow-lg shadow-black/5"><div className="flex items-end gap-2"><input ref={fileRef} type="file" multiple accept=".txt,.md,.csv,.json,.pdf,.docx,.xlsx" className="sr-only" onChange={(event) => chooseFiles(event.target.files)} /><button type="button" onClick={() => fileRef.current?.click()} aria-label="Attach files" className="mb-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl text-text-muted hover:bg-cream-highlight hover:text-accent"><Paperclip className="h-4 w-4" /></button><textarea ref={inputRef} value={goal} onChange={(event) => { setGoal(event.target.value); setError(null); }} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void submit(event); } }} rows={1} placeholder={activeTask ? "Continue the task or start a new Agent goal…" : "Ask anything or give a task to the Agent…"} aria-label="Agent goal input" className="max-h-28 min-h-9 flex-1 resize-none bg-transparent px-2 py-2 text-sm leading-5 text-text-main outline-none placeholder:text-text-muted/60" /><button type="submit" disabled={!goal.trim()} className="mb-1 flex h-9 items-center gap-1.5 rounded-xl bg-sidebar-cocoa px-3 text-xs font-semibold text-white transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"><Send className="h-3.5 w-3.5" /><span className="hidden sm:inline">Send</span></button></div>{files.length > 0 && <div className="flex flex-wrap gap-2 px-10 pb-1 pt-1">{files.map((file, index) => <span key={`${file.name}-${file.size}`} className="flex items-center gap-1 rounded-md bg-cream-highlight px-2 py-1 text-[10px] text-text-main"><Paperclip className="h-3 w-3 text-accent" />{file.name}<button type="button" onClick={() => setFiles((items) => items.filter((_, itemIndex) => itemIndex !== index))} aria-label={`Remove ${file.name}`}><X className="h-3 w-3 text-text-muted" /></button></span>)}</div>}</div><div className="mt-2 flex items-center gap-2 overflow-x-auto pb-0.5">{QUICK_ACTIONS.map((action) => <button key={action.label} type="button" onClick={() => handleQuickAction(action.prompt)} className="flex shrink-0 items-center gap-1.5 rounded-lg border border-border-main/70 bg-surface px-2.5 py-1.5 text-[10px] font-semibold text-text-muted hover:border-accent/30 hover:bg-cream-highlight hover:text-accent">{action.icon}{action.label}</button>)}<span className="ml-auto hidden shrink-0 items-center gap-1 text-[10px] text-text-muted lg:flex"><Plus className="h-3 w-3" />Shift+Enter for a new line</span></div>{error && <p role="alert" className="mt-1 px-1 text-[10px] font-medium text-red-600">{error}</p>}</form></section>;
}
async function toAttachment(file: File): Promise<AgentAttachment> { const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error || new Error(`Could not read ${file.name}`)); reader.readAsDataURL(file); }); return { id: crypto.randomUUID(), filename: file.name, mediaType: file.type || inferType(file.name), sizeBytes: file.size, dataUrl }; }
function inferType(filename: string): string { const extension = filename.toLowerCase().split(".").pop(); if (extension === "pdf") return "application/pdf"; if (extension === "docx") return "application/vnd.openxmlformats-officedocument.wordprocessingml.document"; if (extension === "xlsx") return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"; if (extension === "json") return "application/json"; if (extension === "csv") return "text/csv"; if (extension === "md") return "text/markdown"; return "text/plain"; }
